# Generated by Django 5.2.6 on 2025-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(blank=True, help_text='URL to restaurant image stored in Supabase', max_length=500, null=True),
        ),
    ]
