# Generated by Django 5.2.6 on 2025-12-01 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street_block', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('price_min', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_max', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_guest_count', models.IntegerField()),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('operating_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat,Sun', max_length=100)),
                ('image', models.CharField(blank=True, help_text='URL to restaurant image stored in Supabase', max_length=500, null=True)),
                ('proof_of_ownership', models.CharField(blank=True, help_text='URL to proof of ownership document', max_length=500, null=True)),
                ('custom_tags', models.TextField(blank=True, help_text='Comma-separated custom tags', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for rejection/acceptance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_creation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
