# Generated by Django 5.2.8 on 2025-11-10 10:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt_full_name', models.CharField(max_length=255)),
                ('government_id_type', models.CharField(choices=[('DL', 'Driver’s License'), ('PP', 'Passport'), ('NID', 'National ID'), ('OTH', 'Other')], max_length=10)),
                ('government_id_number', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_license', models.FileField(blank=True, null=True, upload_to='owner_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('government_id_front', models.FileField(blank=True, null=True, upload_to='owner_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('government_id_back', models.FileField(blank=True, null=True, upload_to='owner_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('proof_of_ownership', models.FileField(blank=True, null=True, upload_to='owner_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_verification_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
