# Generated by Django 5.2.8 on 2025-11-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerverificationrequest',
            old_name='government_id_doc',
            new_name='government_id_back',
        ),
        migrations.RenameField(
            model_name='ownerverificationrequest',
            old_name='id_number',
            new_name='government_id_number',
        ),
        migrations.RenameField(
            model_name='ownerverificationrequest',
            old_name='gov_full_name',
            new_name='govt_full_name',
        ),
        migrations.RenameField(
            model_name='ownerverificationrequest',
            old_name='proof_ownership',
            new_name='proof_of_ownership',
        ),
        migrations.RemoveField(
            model_name='ownerverificationrequest',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='ownerverificationrequest',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='government_id_front',
            field=models.FileField(default='', upload_to='owner_verification/government_ids/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='government_id_type',
            field=models.CharField(default='Not Provided', max_length=100),
            preserve_default=False,
        ),
    ]
