# Generated by Django 5.2.6 on 2025-12-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_image',
            field=models.URLField(blank=True, help_text='URL to restaurant image stored in Supabase', null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_max_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_operating_days',
            field=models.CharField(blank=True, default='Mon,Tue,Wed,Thu,Fri,Sat,Sun', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_street_block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_street_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='restaurant_street_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
