# Generated by Django 5.2.6 on 2025-12-02 09:31

from django.db import migrations, models


def add_restaurant_fields_if_not_exists(apps, schema_editor):
    """Add restaurant fields only if they don't already exist"""
    db_alias = schema_editor.connection.alias
    
    # List of fields to add with their SQL definitions (all nullable)
    fields_to_add = [
        ('restaurant_name', 'VARCHAR(100)'),
        ('restaurant_phone', 'VARCHAR(20)'),
        ('restaurant_description', 'TEXT'),
        ('restaurant_street_number', 'VARCHAR(50)'),
        ('restaurant_street_name', 'VARCHAR(100)'),
        ('restaurant_street_block', 'VARCHAR(100)'),
        ('restaurant_city', 'VARCHAR(100)'),
        ('restaurant_postal_code', 'VARCHAR(20)'),
        ('restaurant_price_min', 'NUMERIC(8, 2) DEFAULT 0'),
        ('restaurant_price_max', 'NUMERIC(8, 2) DEFAULT 0'),
        ('restaurant_max_guests', 'INTEGER'),
        ('restaurant_opening_time', 'TIME'),
        ('restaurant_closing_time', 'TIME'),
        ('restaurant_operating_days', 'VARCHAR(100) DEFAULT \'Mon,Tue,Wed,Thu,Fri,Sat,Sun\''),
        ('restaurant_image', 'VARCHAR(500)'),
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for field_name, field_type in fields_to_add:
            # Check if column exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='owner_verification_ownerverificationrequest' 
                AND column_name=%s
            """, [field_name])
            
            if not cursor.fetchone():
                # Column doesn't exist, add it
                cursor.execute(f"""
                    ALTER TABLE owner_verification_ownerverificationrequest 
                    ADD COLUMN {field_name} {field_type}
                """)


def remove_restaurant_fields(apps, schema_editor):
    """Remove restaurant fields if they exist"""
    db_alias = schema_editor.connection.alias
    
    fields_to_remove = [
        'restaurant_name', 'restaurant_phone', 'restaurant_description',
        'restaurant_street_number', 'restaurant_street_name', 'restaurant_street_block',
        'restaurant_city', 'restaurant_postal_code', 'restaurant_price_min',
        'restaurant_price_max', 'restaurant_max_guests', 'restaurant_opening_time',
        'restaurant_closing_time', 'restaurant_operating_days', 'restaurant_image',
    ]
    
    with schema_editor.connection.cursor() as cursor:
        for field_name in fields_to_remove:
            # Check if column exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='owner_verification_ownerverificationrequest' 
                AND column_name=%s
            """, [field_name])
            
            if cursor.fetchone():
                # Column exists, remove it
                cursor.execute(f"""
                    ALTER TABLE owner_verification_ownerverificationrequest 
                    DROP COLUMN {field_name}
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('owner_verification', '0002_ownerverificationrequest_restaurant_city_and_more'),
    ]

    operations = [
        migrations.RunPython(add_restaurant_fields_if_not_exists, remove_restaurant_fields),
    ]
