# Generated by Django 5.2.6 on 2025-11-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_verification', '0002_rename_government_id_doc_ownerverificationrequest_government_id_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerverificationrequest',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ownerverificationrequest',
            name='government_id_type',
            field=models.CharField(max_length=50),
        ),
    ]
