# Generated by Django 5.2.8 on 2025-11-17 17:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=800, help_text='Floor plan canvas width in pixels')),
                ('height', models.IntegerField(default=500, help_text='Floor plan canvas height in pixels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floorplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='restaurants.floorplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100, null=True)),
                ('street_block', models.CharField(blank=True, help_text='Block or District', max_length=100, null=True)),
                ('street_name', models.CharField(blank=True, help_text='Street name', max_length=100, null=True)),
                ('street_number', models.CharField(blank=True, help_text='Building/House number', max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('price_min', models.DecimalField(decimal_places=2, default=0, help_text='Minimum food price', max_digits=8)),
                ('price_max', models.DecimalField(decimal_places=2, default=0, help_text='Maximum food price', max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('description', models.TextField()),
                ('max_guest_count', models.IntegerField()),
                ('opening_time', models.TimeField(blank=True, help_text='Restaurant opening time', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Restaurant closing time', null=True)),
                ('operating_days', models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat,Sun', help_text='Comma-separated list of operating days (e.g., Mon,Tue,Wed,Thu,Fri,Sat,Sun)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customers', models.ManyToManyField(blank=True, related_name='restaurants', to='accounts.customer')),
                ('hosts', models.ManyToManyField(blank=True, related_name='restaurants', to='accounts.host')),
                ('managers', models.ManyToManyField(blank=True, related_name='restaurants', to='accounts.manager')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='accounts.owner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='floorplan',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorplan', to='restaurants.restaurant'),
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ManyToManyField(related_name='cuisines', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.customer')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'AVAILABLE'), ('reserved', 'RESERVED')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floorplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.floorplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('restaurants', models.ManyToManyField(blank=True, related_name='tags', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
    ]
