# Generated by Django 5.2.6 on 2025-11-07 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='height',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='width',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='x',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='element',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='x',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='y',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
