# Generated by Django 5.2.6 on 2025-11-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='operating_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat,Sun', help_text='Comma-separated list of operating days (e.g., Mon,Tue,Wed,Thu,Fri,Sat,Sun)', max_length=100),
            preserve_default=False,
        ),
    ]
