# Generated by Django 5.2.6 on 2025-11-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_element_height_element_width_alter_element_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floorplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=1000, help_text='Floor plan canvas width in pixels')),
                ('height', models.IntegerField(default=600, help_text='Floor plan canvas height in pixels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='floorplan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_floor', to='restaurants.floorplan'),
        ),
    ]
