# Generated by Django 5.2.6 on 2025-11-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_operating_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street_block',
            field=models.CharField(blank=True, help_text='Block or District', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street_name',
            field=models.CharField(blank=True, help_text='Street name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street_number',
            field=models.CharField(blank=True, help_text='Building/House number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='operating_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri,Sat,Sun', help_text='Comma-separated list of operating days (e.g., Mon,Tue,Wed,Thu,Fri,Sat,Sun)', max_length=100),
        ),
    ]
