# Generated by Django 5.2.6 on 2025-11-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_floorplan_restaurant_floorplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='floorplan',
        ),
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='element',
            name='floorplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='restaurants.floorplan'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floorplan', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='table',
            name='floorplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.floorplan'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='height',
            field=models.IntegerField(default=500, help_text='Floor plan canvas height in pixels'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='width',
            field=models.IntegerField(default=800, help_text='Floor plan canvas width in pixels'),
        ),
    ]
