# Generated by Django 5.2.6 - Remove legacy address field

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_migrate_address_to_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
    ]