# Generated by Django 5.2.6 on 2025-11-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_element_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='customer',
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('reserved', 'RESERVED'), ('occupied', 'OCCUPIED'), ('cleaning', 'CLEANING'), ('unavailable', 'UNAVAILABLE')], default='available', max_length=20),
        ),
    ]
