# Generated by Django 5.2.8 on 2025-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_table_customer_alter_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'AVAILABLE'), ('reserved', 'RESERVED')], default='available', max_length=20),
        ),
    ]
