# Generated by Django 5.2.6 on 2025-11-03 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number'),
        ('restaurants', '0006_restaurant_owner_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='accounts.owner'),
        ),
    ]
