# Generated by Django 5.2.6 on 2025-11-14 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('restaurants', '0006_alter_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='accounts.host'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='accounts.manager'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='accounts.owner'),
        ),
    ]
