# Generated by Django 5.2.6 on 2025-10-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
