# Generated by Django 5.2.6 on 2025-11-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
