# Generated by Django 5.2.6 on 2025-11-18 13:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='business_email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='business_license',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='government_id_back',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='government_id_front',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='government_id_number',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='government_id_type',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='govt_full_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='proof_of_ownership',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='status',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
