# Generated by Django 5.2.6 on 2025-12-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_server'),
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
    ]
