# Generated by Django 5.2.8 on 2025-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='ownership_docs/licenses/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='government_id_doc',
            field=models.FileField(blank=True, null=True, upload_to='ownership_docs/ids/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='government_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='govt_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='proof_ownership',
            field=models.FileField(blank=True, null=True, upload_to='ownership_docs/proofs/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
