# Generated by Django 5.2.6 on 2025-12-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_owner_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, help_text='URL to profile image stored in Supabase', max_length=500, null=True),
        ),
    ]
