# Generated by Django 5.2.6 on 2025-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OWNER', 'Owner'), ('HOST', 'Host'), ('MANAGER', 'Manager')], default='CUSTOMER', max_length=20),
        ),
    ]
