# Generated by Django 5.2.8 on 2025-11-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_owner_business_address_owner_business_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='government_id_doc',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='proof_ownership',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='owner',
            name='government_id_back',
            field=models.FileField(blank=True, null=True, upload_to='govt_ids/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='government_id_front',
            field=models.FileField(blank=True, null=True, upload_to='govt_ids/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='government_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='proof_of_ownership',
            field=models.FileField(blank=True, null=True, upload_to='ownership_proofs/'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='business_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='business_licenses/'),
        ),
    ]
