# Generated by Django 5.2.6 on 2025-11-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_owner_business_address_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS accounts_server CASCADE;",
            reverse_sql="CREATE TABLE accounts_server (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES accounts_user(id) ON DELETE CASCADE);",
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
