# Generated by Django 5.2.8 on 2025-11-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('accounts', '0004_owner_status_alter_owner_user'),
    ]

    operations = [
    ]
