# Generated by Django 5.2.6 on 2025-11-18 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt_full_name', models.CharField(max_length=255)),
                ('government_id_type', models.CharField(max_length=50)),
                ('government_id_number', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=255)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('business_license', models.URLField(blank=True, null=True)),
                ('government_id_front', models.URLField(blank=True, null=True)),
                ('government_id_back', models.URLField(blank=True, null=True)),
                ('proof_of_ownership', models.URLField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('NOT_APPROVED', 'Not Approved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
